# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RPC
version:      0.4
version_from: lib/XML/RPC.pm
installdirs:  site
requires:
    XML::TreePP:                    0
    LWP::UserAgent:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
